server:
  port: 8090

spring:
  application:
    name: "course-service"

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: ''
    driverClassName: org.h2.Driver

  h2:
    console:
      enabled: true

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect

  management:
    endpoints:
      web:
        exposure:
          include: "*"

  feign:
    client:
      config:
        employee-service:
          url: http://employee-service:8080  # Use service name for Docker networking
        enrollment-service:
          url: http://enrollment-service:8081  # Use service name for Docker networking
