server:
  port: 8090

spring:
  application:
    name: "course-service"

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: ''
    driverClassName: org.h2.Driver

  h2:
    console:
      enabled: true

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect

  management:
    endpoints:
      web:
        exposure:
          include: "*"

enrollment:
  service:
    url: http://localhost:8081  # URL for the Enrollment service (needed for Course service)
